version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  go-app:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: go_app
    volumes:
      - ./go:/app
    environment:
      POSTGRES_URL: postgres://postgres:postgres@postgres-db:5432/sensor_db?sslmode=disable
    ports:
      - "5000:8080"
    depends_on:
      - postgres-db
    restart: always # Optional: Restart the container if it stops

volumes:
  postgres_data:
